name: cld
channels:
  - pytorch
  - nvidia
  - menpo
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.4.0
  - argon2-cffi=21.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - certifi=2024.7.4
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - einops=0.8.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3
  - fire=0.7.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - hyperframe=6.0.1
  - icu=73.1
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipywidgets=8.0.3
  - isoduration=20.11.0
  - jedi=0.19.1
  - jpeg=9e
  - json5=0.9.6
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.4.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.11
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcups=2.4.2
  - libcurand=10.3.6.82
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - minio=7.2.8
  - mkl=2023.1.0
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclient=0.5.11
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - notebook-shim=0.2.4
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre=8.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.18.0
  - pyqt=5.15.10
  - python=3.12.0
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.35.1
  - scienceplots=2.1.1
  - setuptools=71.0.4
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.13.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - timm=1.0.13
  - tk=8.6.12
  - traitlets=5.14.3
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - attrs==23.1.0
    - azure-core==1.30.2
    - azure-storage-blob==12.21.0
    - babel==2.11.0
    - beautifulsoup4==4.12.2
    - bottleneck==1.3.5
    - brotli==1.0.9
    - cffi==1.16.0
    - contourpy==1.0.5
    - cryptography==41.0.3
    - debugpy==1.6.7
    - entrypoints==0.4
    - exceptiongroup==1.0.4
    - fastjsonschema==2.16.2
    - filelock==3.9.0
    - fsspec==2024.6.1
    - h2==4.0.0
    - huggingface-hub==0.24.6
    - idna==3.4
    - ipykernel==6.28.0
    - ipython==8.15.0
    - isodate==0.6.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jupyter==1.1.1
    - jupyter-core==5.7.2
    - jupyterlab==4.3.4
    - kiwisolver==1.4.4
    - littleutils==0.2.4
    - markupsafe==2.1.1
    - matplotlib==3.8.0
    - mistune==2.0.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - networkx==3.1
    - notebook==7.3.2
    - numexpr==2.8.7
    - numpy==1.26.0
    - ogb==1.3.6
    - opencv-python==4.10.0.84
    - outdated==0.2.2
    - pandas==2.1.1
    - pillow==10.0.1
    - ply==3.11
    - prometheus-client==0.14.1
    - psutil==5.9.0
    - pycryptodome==3.20.0
    - pyopenssl==23.2.0
    - pyparsing==3.0.9
    - pyqt5==5.15.10
    - pyqt5-sip==12.13.0
    - pysocks==1.7.1
    - python-json-logger==2.0.7
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - safetensors==0.4.5
    - scikit-learn==1.3.0
    - scipy==1.11.3
    - seaborn==0.12.2
    - send2trash==1.8.2
    - sip==6.7.12
    - sniffio==1.2.0
    - soupsieve==2.5
    - termcolor==2.1.0
    - terminado==0.17.1
    - thop==0.1.1-2209072238
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==2.3.1
    - torchvision==0.18.1
    - tornado==6.3.3
    - tqdm==4.66.5
    - typing-extensions==4.7.1
    - urllib3==1.26.18
    - webencodings==0.5.1
    - widgetsnbextension==4.0.5
    - wilds==2.0.0
